export const USERS_CONSTANTS = {
    USERS_LIST_LOAD_REQUEST: 'USERS_LIST_LOAD_REQUEST',
    USERS_LIST_LOAD_SUCCESS: 'USERS_LIST_LOAD_SUCCESS',
    USERS_LIST_LOAD_FAILURE: 'USERS_LIST_LOAD_FAILURE',
    USERS_LIST_UPDATE_REQUEST: 'USERS_LIST_UPDATE_REQUEST',
    USERS_LIST_UPDATE_SUCCESS: 'USERS_LIST_UPDATE_SUCCESS',
    USERS_LIST_UPDATE_FAILURE: 'USERS_LIST_UPDATE_FAILURE',
}
  